/* eslint-disable */
// This file is generated by miqi.runtime.export_app_protocol_ts.
// Do not edit by hand; update Python request models and regenerate.

export const APP_PROTOCOL_GENERATED_AT = 'static' as const

export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue }
export type EmptyObject = Record<string, never>

export interface CommandExecParams {
  command: string[]
  cwd?: null | string
  deltaBase64?: null | string
  disableOutputCap?: boolean
  disableTimeout?: boolean
  env?: Record<string, unknown> | null
  outputBytesCap?: null | number
  processId?: null | string
  size?: null | unknown
  streamStdin?: boolean
  streamStdoutStderr?: boolean
  timeoutMs?: null | number
  tty?: boolean
}

export interface CommandExecResizeParams {
  processId?: null | string
}

export interface CommandExecTerminateParams {
  processId: string
}

export interface CommandExecWriteParams {
  closeStdin?: boolean
  deltaBase64?: null | string
  processId: string
}

export interface FsCopyParams {
  destinationPath: string
  recursive?: boolean
  sourcePath: string
}

export interface FsCreateDirectoryParams {
  path: string
  recursive?: boolean
}

export interface FsGetMetadataParams {
  path: string
}

export interface FsReadDirectoryParams {
  path: string
}

export interface FsReadFileParams {
  path: string
}

export interface FsRemoveParams {
  force?: boolean
  path: string
  recursive?: boolean
}

export interface FsUnwatchParams {
  watchId: string
}

export interface FsWatchParams {
  path: string
  watchId: string
}

export interface FsWriteFileParams {
  dataBase64: string
  path: string
}

export interface FuzzyFileSearchParams {
  query: string
  roots: string[]
}

export interface FuzzySessionStartParams {
  roots: string[]
  sessionId: string
}

export interface FuzzySessionStopParams {
  sessionId: string
}

export interface FuzzySessionUpdateParams {
  query: string
  sessionId: string
}

export interface ProcessKillParams {
  processHandle: string
}

export interface ProcessResizePtyParams {
  processHandle?: null | string
}

export interface ProcessSpawnParams {
  command: string[]
  cwd: string
  disableOutputCap?: boolean
  disableTimeout?: boolean
  env?: Record<string, unknown> | null
  outputBytesCap?: null | number
  processHandle: string
  streamStdoutStderr?: boolean
  timeoutMs?: null | number
  tty?: boolean
}

export interface ProcessWriteStdinParams {
  closeStdin?: boolean
  deltaBase64?: null | string
  processHandle: string
}

export interface ThreadCompactStartParams {
  threadId: string
}

export interface ThreadInjectItemsParams {
  items: Record<string, unknown>[]
  threadId: string
}

export interface TurnInterruptParams {
  threadId: string
  turnId: string
}

export interface TurnStartParams {
  clientUserMessageId?: null | string
  effort?: null | string
  environments?: null | unknown
  input: Record<string, unknown>[]
  model?: null | string
  outputSchema?: null | unknown
  personality?: null | string
  summary?: null | string
  threadId: string
}

export interface TurnSteerParams {
  clientUserMessageId?: null | string
  expectedTurnId: string
  input: Record<string, unknown>[]
  threadId: string
}

export const APP_METHODS = [
  'command/exec',
  'command/exec/resize',
  'command/exec/terminate',
  'command/exec/write',
  'fs/copy',
  'fs/createDirectory',
  'fs/getMetadata',
  'fs/readDirectory',
  'fs/readFile',
  'fs/remove',
  'fs/unwatch',
  'fs/watch',
  'fs/writeFile',
  'fuzzyFileSearch',
  'fuzzyFileSearch/sessionStart',
  'fuzzyFileSearch/sessionStop',
  'fuzzyFileSearch/sessionUpdate',
  'process/kill',
  'process/resizePty',
  'process/spawn',
  'process/writeStdin',
  'thread/compact/start',
  'thread/inject_items',
  'turn/interrupt',
  'turn/start',
  'turn/steer',
] as const
export type AppMethod = typeof APP_METHODS[number]

export interface AppMethodParams {
  'command/exec': CommandExecParams
  'command/exec/resize': CommandExecResizeParams
  'command/exec/terminate': CommandExecTerminateParams
  'command/exec/write': CommandExecWriteParams
  'fs/copy': FsCopyParams
  'fs/createDirectory': FsCreateDirectoryParams
  'fs/getMetadata': FsGetMetadataParams
  'fs/readDirectory': FsReadDirectoryParams
  'fs/readFile': FsReadFileParams
  'fs/remove': FsRemoveParams
  'fs/unwatch': FsUnwatchParams
  'fs/watch': FsWatchParams
  'fs/writeFile': FsWriteFileParams
  'fuzzyFileSearch': FuzzyFileSearchParams
  'fuzzyFileSearch/sessionStart': FuzzySessionStartParams
  'fuzzyFileSearch/sessionStop': FuzzySessionStopParams
  'fuzzyFileSearch/sessionUpdate': FuzzySessionUpdateParams
  'process/kill': ProcessKillParams
  'process/resizePty': ProcessResizePtyParams
  'process/spawn': ProcessSpawnParams
  'process/writeStdin': ProcessWriteStdinParams
  'thread/compact/start': ThreadCompactStartParams
  'thread/inject_items': ThreadInjectItemsParams
  'turn/interrupt': TurnInterruptParams
  'turn/start': TurnStartParams
  'turn/steer': TurnSteerParams
}

export interface AppMethodResult {
  'command/exec': Record<string, unknown>
  'command/exec/resize': Record<string, unknown>
  'command/exec/terminate': Record<string, unknown>
  'command/exec/write': Record<string, unknown>
  'fs/copy': Record<string, never>
  'fs/createDirectory': Record<string, never>
  'fs/getMetadata': { isDirectory: boolean; isFile: boolean; isSymlink: boolean; createdAtMs: number; modifiedAtMs: number }
  'fs/readDirectory': { entries: Array<{ fileName: string; isDirectory: boolean; isFile: boolean }> }
  'fs/readFile': { dataBase64: string }
  'fs/remove': Record<string, never>
  'fs/unwatch': Record<string, never>
  'fs/watch': Record<string, unknown>
  'fs/writeFile': Record<string, never>
  'fuzzyFileSearch': { files: string[] }
  'fuzzyFileSearch/sessionStart': Record<string, never>
  'fuzzyFileSearch/sessionStop': Record<string, never>
  'fuzzyFileSearch/sessionUpdate': Record<string, never>
  'process/kill': Record<string, unknown>
  'process/resizePty': Record<string, unknown>
  'process/spawn': Record<string, unknown>
  'process/writeStdin': Record<string, unknown>
  'thread/compact/start': Record<string, unknown>
  'thread/inject_items': Record<string, unknown>
  'turn/interrupt': Record<string, unknown>
  'turn/start': Record<string, unknown>
  'turn/steer': Record<string, unknown>
}

export interface AppMethodEvents {
  'command/exec': never
  'command/exec/resize': never
  'command/exec/terminate': never
  'command/exec/write': never
  'fs/copy': never
  'fs/createDirectory': never
  'fs/getMetadata': never
  'fs/readDirectory': never
  'fs/readFile': never
  'fs/remove': never
  'fs/unwatch': never
  'fs/watch': 'fs/changed'
  'fs/writeFile': never
  'fuzzyFileSearch': never
  'fuzzyFileSearch/sessionStart': never
  'fuzzyFileSearch/sessionStop': never
  'fuzzyFileSearch/sessionUpdate': never
  'process/kill': never
  'process/resizePty': never
  'process/spawn': never
  'process/writeStdin': never
  'thread/compact/start': 'item/completed' | 'item/started' | 'turn/completed' | 'turn/started'
  'thread/inject_items': never
  'turn/interrupt': never
  'turn/start': 'item/completed' | 'item/started' | 'turn/completed' | 'turn/started'
  'turn/steer': never
}

export type AppRequest<M extends AppMethod = AppMethod> = {
  id: string
  method: M
  params: AppMethodParams[M]
}

export type AppResult<M extends AppMethod> = AppMethodResult[M]
export type AppParams<M extends AppMethod> = AppMethodParams[M]
export type AppEvent<M extends AppMethod> = AppMethodEvents[M]
