/* eslint-disable */
// This file is generated by miqi.runtime.export_app_protocol_ts.
// Do not edit by hand; update Python request models and regenerate.

export const APP_PROTOCOL_GENERATED_AT = 'static' as const

export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue }
export type EmptyObject = Record<string, never>

export interface CommandExecParams {
  command: string[]
  cwd?: null | string
  deltaBase64?: null | string
  disableOutputCap?: boolean
  disableTimeout?: boolean
  env?: Record<string, unknown> | null
  outputBytesCap?: null | number
  processId?: null | string
  size?: null | unknown
  streamStdin?: boolean
  streamStdoutStderr?: boolean
  timeoutMs?: null | number
  tty?: boolean
}

export interface CommandExecResizeParams {
  processId?: null | string
}

export interface CommandExecTerminateParams {
  processId: string
}

export interface CommandExecWriteParams {
  closeStdin?: boolean
  deltaBase64?: null | string
  processId: string
}

export interface FsCopyParams {
  destinationPath: string
  recursive?: boolean
  sourcePath: string
}

export interface FsCreateDirectoryParams {
  path: string
  recursive?: boolean
}

export interface FsGetMetadataParams {
  path: string
}

export interface FsReadDirectoryParams {
  path: string
}

export interface FsReadFileParams {
  path: string
}

export interface FsRemoveParams {
  force?: boolean
  path: string
  recursive?: boolean
}

export interface FsUnwatchParams {
  watchId: string
}

export interface FsWatchParams {
  path: string
  watchId: string
}

export interface FsWriteFileParams {
  dataBase64: string
  path: string
}

export interface FuzzyFileSearchParams {
  query: string
  roots: string[]
}

export interface FuzzySessionStartParams {
  roots: string[]
  sessionId: string
}

export interface FuzzySessionStopParams {
  sessionId: string
}

export interface FuzzySessionUpdateParams {
  query: string
  sessionId: string
}

export interface ProcessKillParams {
  processHandle: string
}

export interface ProcessResizePtyParams {
  processHandle?: null | string
}

export interface ProcessSpawnParams {
  command: string[]
  cwd: string
  disableOutputCap?: boolean
  disableTimeout?: boolean
  env?: Record<string, unknown> | null
  outputBytesCap?: null | number
  processHandle: string
  streamStdoutStderr?: boolean
  timeoutMs?: null | number
  tty?: boolean
}

export interface ProcessWriteStdinParams {
  closeStdin?: boolean
  deltaBase64?: null | string
  processHandle: string
}

export interface ThreadCompactStartParams {
  threadId: string
}

export interface ThreadInjectItemsParams {
  items: Record<string, unknown>[]
  threadId: string
}

export interface TurnInterruptParams {
  threadId: string
  turnId: string
}

export interface TurnStartParams {
  clientUserMessageId?: null | string
  effort?: null | string
  environments?: null | unknown
  input: Record<string, unknown>[]
  model?: null | string
  outputSchema?: null | unknown
  personality?: null | string
  summary?: null | string
  threadId: string
}

export interface TurnSteerParams {
  clientUserMessageId?: null | string
  expectedTurnId: string
  input: Record<string, unknown>[]
  threadId: string
}

export interface CommandExecResult {
  durationMs: number
  exitCode: number
  stderr: string
  stderrCapReached: boolean
  stdout: string
  stdoutCapReached: boolean
  terminationReason: null | string
}

export interface CommandExecResizeResult {
}

export interface CommandExecTerminateResult {
}

export interface CommandExecWriteResult {
}

export interface FsCopyResult {
}

export interface FsCreateDirectoryResult {
}

export interface FsGetMetadataResult {
  createdAtMs: number
  isDirectory: boolean
  isFile: boolean
  isSymlink: boolean
  modifiedAtMs: number
}

export interface FsReadDirectoryResult {
  entries: unknown[]
}

export interface FsReadFileResult {
  dataBase64: string
}

export interface FsRemoveResult {
}

export interface FsUnwatchResult {
}

export interface FsWatchResult {
  path: string
}

export interface FsWriteFileResult {
}

export interface FuzzyFileSearchResult {
  files: unknown[]
}

export interface FuzzySessionStartResult {
}

export interface FuzzySessionStopResult {
}

export interface FuzzySessionUpdateResult {
}

export interface ProcessKillResult {
}

export interface ProcessResizePtyResult {
}

export interface ProcessSpawnResult {
}

export interface ProcessWriteStdinResult {
}

export interface CommandExecOutputDeltaEventPayload {
  capReached: boolean
  deltaBase64: string
  processId: string
  stream: string
}

export interface FsChangedEventPayload {
  changedPaths: string[]
  watchId: string
}

export interface FuzzySessionCompletedEventPayload {
  sessionId: string
}

export interface FuzzySessionUpdatedEventPayload {
  files: unknown[]
  query: string
  sessionId: string
}

export interface ProcessExitedEventPayload {
  durationMs: number
  exitCode: number
  processHandle: string
  stderr: string
  stderrCapReached: boolean
  stdout: string
  stdoutCapReached: boolean
  terminationReason: null | string
}

export interface ProcessOutputDeltaEventPayload {
  capReached: boolean
  deltaBase64: string
  processHandle: string
  stream: string
}

export const APP_METHODS = [
  'command/exec',
  'command/exec/resize',
  'command/exec/terminate',
  'command/exec/write',
  'fs/copy',
  'fs/createDirectory',
  'fs/getMetadata',
  'fs/readDirectory',
  'fs/readFile',
  'fs/remove',
  'fs/unwatch',
  'fs/watch',
  'fs/writeFile',
  'fuzzyFileSearch',
  'fuzzyFileSearch/sessionStart',
  'fuzzyFileSearch/sessionStop',
  'fuzzyFileSearch/sessionUpdate',
  'process/kill',
  'process/resizePty',
  'process/spawn',
  'process/writeStdin',
  'thread/compact/start',
  'thread/inject_items',
  'turn/interrupt',
  'turn/start',
  'turn/steer',
] as const
export type AppMethod = typeof APP_METHODS[number]

export interface AppMethodParams {
  'command/exec': CommandExecParams
  'command/exec/resize': CommandExecResizeParams
  'command/exec/terminate': CommandExecTerminateParams
  'command/exec/write': CommandExecWriteParams
  'fs/copy': FsCopyParams
  'fs/createDirectory': FsCreateDirectoryParams
  'fs/getMetadata': FsGetMetadataParams
  'fs/readDirectory': FsReadDirectoryParams
  'fs/readFile': FsReadFileParams
  'fs/remove': FsRemoveParams
  'fs/unwatch': FsUnwatchParams
  'fs/watch': FsWatchParams
  'fs/writeFile': FsWriteFileParams
  'fuzzyFileSearch': FuzzyFileSearchParams
  'fuzzyFileSearch/sessionStart': FuzzySessionStartParams
  'fuzzyFileSearch/sessionStop': FuzzySessionStopParams
  'fuzzyFileSearch/sessionUpdate': FuzzySessionUpdateParams
  'process/kill': ProcessKillParams
  'process/resizePty': ProcessResizePtyParams
  'process/spawn': ProcessSpawnParams
  'process/writeStdin': ProcessWriteStdinParams
  'thread/compact/start': ThreadCompactStartParams
  'thread/inject_items': ThreadInjectItemsParams
  'turn/interrupt': TurnInterruptParams
  'turn/start': TurnStartParams
  'turn/steer': TurnSteerParams
}

export interface AppMethodResult {
  'command/exec': CommandExecResult
  'command/exec/resize': CommandExecResizeResult
  'command/exec/terminate': CommandExecTerminateResult
  'command/exec/write': CommandExecWriteResult
  'fs/copy': FsCopyResult
  'fs/createDirectory': FsCreateDirectoryResult
  'fs/getMetadata': FsGetMetadataResult
  'fs/readDirectory': FsReadDirectoryResult
  'fs/readFile': FsReadFileResult
  'fs/remove': FsRemoveResult
  'fs/unwatch': FsUnwatchResult
  'fs/watch': FsWatchResult
  'fs/writeFile': FsWriteFileResult
  'fuzzyFileSearch': FuzzyFileSearchResult
  'fuzzyFileSearch/sessionStart': FuzzySessionStartResult
  'fuzzyFileSearch/sessionStop': FuzzySessionStopResult
  'fuzzyFileSearch/sessionUpdate': FuzzySessionUpdateResult
  'process/kill': ProcessKillResult
  'process/resizePty': ProcessResizePtyResult
  'process/spawn': ProcessSpawnResult
  'process/writeStdin': ProcessWriteStdinResult
  'thread/compact/start': Record<string, unknown>
  'thread/inject_items': Record<string, unknown>
  'turn/interrupt': Record<string, unknown>
  'turn/start': Record<string, unknown>
  'turn/steer': Record<string, unknown>
}

export interface AppMethodEvents {
  'command/exec': 'command/exec/outputDelta'
  'command/exec/resize': never
  'command/exec/terminate': never
  'command/exec/write': never
  'fs/copy': never
  'fs/createDirectory': never
  'fs/getMetadata': never
  'fs/readDirectory': never
  'fs/readFile': never
  'fs/remove': never
  'fs/unwatch': never
  'fs/watch': 'fs/changed'
  'fs/writeFile': never
  'fuzzyFileSearch': never
  'fuzzyFileSearch/sessionStart': never
  'fuzzyFileSearch/sessionStop': never
  'fuzzyFileSearch/sessionUpdate': 'fuzzyFileSearch/sessionCompleted' | 'fuzzyFileSearch/sessionUpdated'
  'process/kill': never
  'process/resizePty': never
  'process/spawn': 'process/exited' | 'process/outputDelta'
  'process/writeStdin': never
  'thread/compact/start': 'item/completed' | 'item/started' | 'turn/completed' | 'turn/started'
  'thread/inject_items': never
  'turn/interrupt': never
  'turn/start': 'item/completed' | 'item/started' | 'turn/completed' | 'turn/started'
  'turn/steer': never
}

export interface AppEventPayloadMap {
  'command/exec/outputDelta': CommandExecOutputDeltaEventPayload
  'fs/changed': FsChangedEventPayload
  'fuzzyFileSearch/sessionCompleted': FuzzySessionCompletedEventPayload
  'fuzzyFileSearch/sessionUpdated': FuzzySessionUpdatedEventPayload
  'process/exited': ProcessExitedEventPayload
  'process/outputDelta': ProcessOutputDeltaEventPayload
}
export type AppEventName = keyof AppEventPayloadMap

export type AppEventPayload<E extends AppEventName> = AppEventPayloadMap[E]

export type AppRequest<M extends AppMethod = AppMethod> = {
  id: string
  method: M
  params: AppMethodParams[M]
}

export type AppResult<M extends AppMethod> = AppMethodResult[M]
export type AppParams<M extends AppMethod> = AppMethodParams[M]
export type AppEvent<M extends AppMethod> = AppMethodEvents[M]
