/**
 * grok-config.ts — Generate ~/.grok/config.toml from MiQi config.
 *
 * Grok is a model-agnostic agent runtime.  When MiQi switches to grok
 * (agents.defaults.model === "grok"), this module scans configured
 * providers for a usable apiKey + apiBase + model, then writes a
 * single-model config.toml before spawning `grok agent stdio`.
 */

import { existsSync, mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface GrokModelConfig {
  modelSlug: string; // always "grok-model"
  modelId: string; // actual model ID
  modelName: string; // display name
  apiBase?: string; // provider apiBase
  apiKey: string; // the apiKey to set as env var
  apiKeyEnvVar: string; // always "MIQI_API_KEY"
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export function grokHome(): string {
  return join(homedir(), '.grok');
}

/**
 * Resolve grok model config from MiQi's configured providers.
 *
 * Priority:
 * 1. agents.defaults.model prefix → matching provider with apiKey + model
 * 2. First configured provider with apiKey (any model)
 * 3. XAI_API_KEY env var → use with model from agents.defaults
 */

/** Per-provider fallback models when no model is configured. */
const KNOWN_DEFAULT_MODELS: Record<string, string> = {
  deepseek: 'deepseek-chat',
  siliconflow: 'deepseek-ai/DeepSeek-V3',
};

export function resolveGrokModelConfig(
  miqiConfig: Record<string, unknown>
): GrokModelConfig | null {
  const agents = (miqiConfig['agents'] as Record<string, unknown> | undefined) ?? {};
  const defaults = (agents['defaults'] as Record<string, unknown> | undefined) ?? {};
  const providers = (miqiConfig['providers'] as Record<string, unknown> | undefined) ?? {};
  const activeModel = (defaults['model'] as string) ?? '';

  // --- Candidate: the provider matching activeModel's prefix ---
  let modelId = '';
  let providerName: string | null = null;
  const slashIdx = activeModel.indexOf('/');
  if (slashIdx !== -1) {
    providerName = activeModel.slice(0, slashIdx);
    modelId = activeModel.slice(slashIdx + 1);
  }

  if (providerName && providerName !== 'grok') {
    const entry = providers[providerName] as Record<string, unknown> | undefined;
    if (entry) {
      const apiKey = (entry['apiKey'] as string) ?? (entry['api_key'] as string) ?? '';
      const apiBase = (entry['apiBase'] as string) ?? (entry['api_base'] as string) ?? undefined;
      if (apiKey) {
        return {
          modelSlug: 'grok-model',
          modelId: modelId || (activeModel !== 'grok' ? activeModel : ''),
          modelName: `${providerName}/${modelId || 'default'}`,
          apiBase,
          apiKey,
          apiKeyEnvVar: 'MIQI_API_KEY',
        };
      }
    }
  }

  // --- Fallback: scan all providers for the first with apiKey ---
  for (const [name, entry] of Object.entries(providers)) {
    if (name === 'grok') continue;
    const e = entry as Record<string, unknown>;
    const apiKey = (e['apiKey'] as string) ?? (e['api_key'] as string) ?? '';
    if (!apiKey) continue;

    const candidateModel = (e['model'] as string) ?? (e['configured_model'] as string) ?? modelId;
    const apiBase = (e['apiBase'] as string) ?? (e['api_base'] as string) ?? undefined;

    return {
      modelSlug: 'grok-model',
      modelId: candidateModel || KNOWN_DEFAULT_MODELS[name] || 'deepseek-chat',
      modelName: `${name}/${candidateModel || 'default'}`,
      apiBase,
      apiKey,
      apiKeyEnvVar: 'MIQI_API_KEY',
    };
  }

  // --- Last resort: env var ---
  const envKey = process.env['XAI_API_KEY'];
  if (envKey) {
    return {
      modelSlug: 'grok-model',
      modelId: modelId || 'gpt-4.1',
      modelName: modelId || 'default',
      apiKey: envKey,
      apiKeyEnvVar: 'MIQI_API_KEY',
    };
  }

  return null;
}

export function generateGrokConfigToml(cfg: GrokModelConfig): string {
  const lines: string[] = [
    '# Generated by MiQi Desktop.',
    '',
    '[models]',
    `default = "${esc(cfg.modelSlug)}"`,
    '',
    `[model.${esc(cfg.modelSlug)}]`,
    `model = "${esc(cfg.modelId)}"`,
    `name = "${esc(cfg.modelName)}"`,
  ];

  if (cfg.apiBase) {
    lines.push(`base_url = "${esc(cfg.apiBase)}"`);
  }

  lines.push(`env_key = "${esc(cfg.apiKeyEnvVar)}"`);

  return lines.join('\n') + '\n';
}

export function writeGrokConfigToml(toml: string): void {
  const dir = grokHome();
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
  const path = join(dir, 'config.toml');
  writeFileSync(path, toml, 'utf8');
}

function esc(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}
